/**
 * fzf's `FuzzyMatchV2`, ported to TypeScript — scores *and* match positions.
 *
 * The picker highlights the characters a query matched, so it needs positions, and
 * positions are exactly what a cheaper matcher gets wrong. A greedy left-to-right
 * subsequence scan finds the same *set* of matching rows, but on this repo's own data it
 * puts the highlight in the wrong place on 28% of branch names and 47% of PR titles: every
 * row begins with an issue key, so a query starting with any letter in `EXC-1010/` latches
 * onto the prefix instead of the words a human was aiming at. Only the full
 * Smith-Waterman-style dynamic program, with a backtrace, recovers fzf's answer.
 *
 * This is a port rather than a dependency because owning it is what makes "is it still in
 * sync with upstream?" a question with an answer. The answer is a golden corpus:
 * `test/golden/fzf.jsonl` holds several thousand cases frozen from the real fzf, and
 * `test/fuzzy.test.ts` replays every one. The corpus is generated by `tools/fzf-golden`,
 * which needs Go and a network; replaying it needs neither.
 *
 * ## Resync trigger
 *
 * Regenerate the corpus (`tools/fzf-golden/main.go` carries the command) and re-check this
 * port when any of these happen:
 *
 * 1. fzf tags a release whose diff touches `src/algo/`. Nothing watches for this — it is a
 *    manual check, and the reason {@link FZF_VERSION} is written down rather than implied.
 * 2. Either side's Unicode tables move — the Go toolchain's `unicode.Version` or the
 *    JavaScript runtime's property-escape data. This is the likeliest trigger in practice
 *    and the least visible, because nothing about it looks like a change to fuzzy matching;
 *    see the note on the property escapes below for what actually diverges.
 *    {@link GO_UNICODE_VERSION} is what the corpus was cut against.
 * 3. The picker starts feeding the matcher input this port does not cover: a non-default
 *    scoring scheme (`--scheme=path`, `--scheme=history`), accent normalisation, or
 *    backward matching. Each is a deliberate omission below, not an oversight.
 * 4. The corpus replay goes red after an edit here. That is the port drifting, not fzf.
 *
 * ## What is deliberately not ported
 *
 * Every omission below is a layer fzf itself documents as behaviour-preserving, and the
 * corpus is what turns that documentation into a test: it was generated through fzf's
 * public entry point, so fzf took these paths wherever they apply while this module took
 * its one general path, and the two agreed on every case.
 *
 * - **`asciiFuzzyIndex`**, the ASCII prefilter that narrows the DP to a window. It is a
 *   speed optimisation, and fzf skips it outright for non-ASCII input. The cells it would
 *   have changed at the window's left edge (`B[0]`, `H0[0]`, `C0[0]`) are never read by the
 *   later phases, so the unnarrowed scan this module performs is the same computation.
 * - **The one- and two-character fast paths** (`fuzzyMatchV2Single`, `fuzzyMatchV2Two`).
 *   fzf ships `disableSingle` / `disableTwo` test hooks precisely so these can be asserted
 *   equivalent to the general path; the corpus contains plenty of one- and two-character
 *   queries, which is that same assertion made from the outside.
 * - **The `FuzzyMatchV1` fallback**. fzf drops to it when the pattern exceeds 1000
 *   characters *or* when `text.length × query.length` exceeds its slab capacity, which is
 *   `100 * 1024` for every fzf worker — and that product is the condition that bites first.
 *   This module always runs the full DP, so it genuinely diverges above that threshold: a
 *   34134-character text against a 3-character query scores 16 here and -1928 in fzf. For a
 *   picker whose rows are branch names and PR titles the product is four orders of
 *   magnitude short of it. Related, and with a threshold far beyond even that: the DP below
 *   stores scores in `Int16Array`, so it wraps on store as fzf's `int16` matrices do, but
 *   the intermediate arithmetic is in JavaScript numbers, so the two also part company once
 *   a score passes 32767.
 * - **Accent normalisation and backward matching** (`normalize`, `forward=false`), neither
 *   of which the picker asks for.
 *
 * @packageDocumentation
 */
// ponytail: exact only while `text.length × query.length` stays under fzf's 100 KiB slab
// (above it fzf switches to its V1 greedy algorithm and this module does not) and while
// both sides' Unicode tables agree. Port `FuzzyMatchV1` and add the threshold check if this
// ever runs over documents rather than list rows.

/**
 * The fzf release this port and its golden corpus were cut from.
 *
 * The corpus file's header line repeats it, and the test asserts the two agree — so this
 * constant cannot quietly fall out of date while the data moves on, or the reverse.
 */
export const FZF_VERSION = "v0.74.2";

/**
 * The Go toolchain's `unicode.Version` at the time the golden corpus was generated.
 *
 * Nothing pins this — `go.mod`'s `go` directive is a minimum, not a pin — yet it decides how
 * every non-ASCII character in the corpus was classified. The corpus header records it and
 * the test asserts it, so a regeneration under a newer toolchain announces itself instead of
 * quietly reclassifying characters. See the property-escape note on {@link IS_LOWER} for
 * what actually diverges when the two sides' tables disagree.
 */
export const GO_UNICODE_VERSION = "15.0.0";

/** A successful match: fzf's score, and which characters it matched. */
export interface FuzzyMatch {
  /** fzf's score. Higher is better; only comparable between matches on the same query. */
  readonly score: number;
  /**
   * Ascending indices of the matched characters, in **code points** — that is, indices into
   * `Array.from(text)`, not UTF-16 offsets into `text`. fzf works in runes and this port
   * follows it, so a highlighter must iterate the text the same way or it will slice
   * astral characters in half.
   */
  readonly positions: readonly number[];
}

// Scoring constants, verbatim from fzf's src/algo/algo.go. The derived forms are kept as
// expressions rather than folded to literals so they stay legible against upstream.

const SCORE_MATCH = 16;
const SCORE_GAP_START = -3;
const SCORE_GAP_EXTENSION = -1;

/** Chosen so a word-boundary bonus is cancelled once the gap grows past ~8 characters. */
const BONUS_BOUNDARY = SCORE_MATCH / 2;
const BONUS_NON_WORD = SCORE_MATCH / 2;
/** camelCase boundaries carry no separator character, so they are worth one point less. */
const BONUS_CAMEL_123 = BONUS_BOUNDARY + SCORE_GAP_EXTENSION;
const BONUS_CONSECUTIVE = -(SCORE_GAP_START + SCORE_GAP_EXTENSION);
/** The query's first character is the one the typist meant most. */
const BONUS_FIRST_CHAR_MULTIPLIER = 2;

// The `default` scheme's two boundary bonuses. fzf's `path` and `history` schemes change
// these and `INITIAL_CHAR_CLASS`; neither is ported.
const BONUS_BOUNDARY_WHITE = BONUS_BOUNDARY + 2;
const BONUS_BOUNDARY_DELIMITER = BONUS_BOUNDARY + 1;

// Character classes, in fzf's declaration order — `bonusFor` branches on `>= NON_WORD`, so
// the numbering is load-bearing rather than incidental.
const CHAR_WHITE = 0;
const CHAR_NON_WORD = 1;
const CHAR_DELIMITER = 2;
const CHAR_LOWER = 3;
const CHAR_UPPER = 4;
const CHAR_LETTER = 5;
const CHAR_NUMBER = 6;
const CHAR_CLASS_COUNT = CHAR_NUMBER + 1;

/** Text is scored as though preceded by whitespace, so position 0 gets a word-start bonus. */
const INITIAL_CHAR_CLASS = CHAR_WHITE;

const DELIMITER_CHARS = "/,:;|";

/**
 * The ASCII members of Go's `whiteChars`.
 *
 * Upstream also lists the bytes `\x85` and `\xA0`, which are unreachable there: the string
 * is scanned byte-wise against ASCII code points only, and both bytes are above 127. They
 * are omitted here rather than carried as decoration that would silently change the table.
 */
const WHITE_CHARS = " \t\n\v\f\r";

const ASCII_MAX = 0x7f;

/** Any numeric array this module indexes; see {@link at}. */
type NumericArray = Uint8Array | Int16Array | Int32Array;

/**
 * Reads `array[index]`, which `noUncheckedIndexedAccess` otherwise types as possibly
 * `undefined`.
 *
 * Every index in this module is derived from the loop bounds that sized the array, so the
 * read is in range by construction. One helper is preferable to a non-null assertion at
 * each of the two dozen call sites in the inner loops.
 */
function at(array: NumericArray, index: number): number {
  return array[index] as number;
}

/** Class of every ASCII code point — fzf's `asciiCharClasses`, built once. */
const ASCII_CHAR_CLASSES: Uint8Array = (() => {
  const classes = new Uint8Array(ASCII_MAX + 1);
  for (let code = 0; code <= ASCII_MAX; code++) {
    const char = String.fromCharCode(code);
    let charClass = CHAR_NON_WORD;
    if (char >= "a" && char <= "z") charClass = CHAR_LOWER;
    else if (char >= "A" && char <= "Z") charClass = CHAR_UPPER;
    else if (char >= "0" && char <= "9") charClass = CHAR_NUMBER;
    else if (WHITE_CHARS.includes(char)) charClass = CHAR_WHITE;
    else if (DELIMITER_CHARS.includes(char)) charClass = CHAR_DELIMITER;
    classes[code] = charClass;
  }
  return classes;
})();

/** fzf's `bonusFor`: the bonus for `charClass` when preceded by `prevClass`. */
function bonusFor(prevClass: number, charClass: number): number {
  if (charClass >= CHAR_NON_WORD) {
    if (prevClass === CHAR_WHITE) return BONUS_BOUNDARY_WHITE;
    if (prevClass === CHAR_DELIMITER) return BONUS_BOUNDARY_DELIMITER;
    if (prevClass === CHAR_NON_WORD) return BONUS_BOUNDARY;
  }
  if (
    (prevClass === CHAR_LOWER && charClass === CHAR_UPPER) ||
    (prevClass !== CHAR_NUMBER && charClass === CHAR_NUMBER)
  ) {
    return BONUS_CAMEL_123;
  }
  if (charClass === CHAR_NON_WORD || charClass === CHAR_DELIMITER) return BONUS_NON_WORD;
  if (charClass === CHAR_WHITE) return BONUS_BOUNDARY_WHITE;
  return 0;
}

/** fzf's `bonusMatrix`, flattened to `prevClass * CHAR_CLASS_COUNT + charClass`. */
const BONUS_MATRIX: Int16Array = (() => {
  const matrix = new Int16Array(CHAR_CLASS_COUNT * CHAR_CLASS_COUNT);
  for (let prevClass = 0; prevClass < CHAR_CLASS_COUNT; prevClass++) {
    for (let charClass = 0; charClass < CHAR_CLASS_COUNT; charClass++) {
      matrix[prevClass * CHAR_CLASS_COUNT + charClass] = bonusFor(prevClass, charClass);
    }
  }
  return matrix;
})();

// Go's unicode predicates, as Unicode property escapes. `\p{White_Space}` and not `\s`:
// JavaScript's `\s` includes U+FEFF, which `unicode.IsSpace` rejects, and excludes U+0085,
// which it accepts. The rest line up by *definition* — note `\p{Lu}` excludes titlecase
// (Lt), which is why `ǅ` never folds.
//
// They do not line up by *table version*. Go's tables ship with the toolchain
// ({@link GO_UNICODE_VERSION}) and the runtime's ship with the runtime, so a code point
// assigned since the older of the two classifies as a letter on one side and as unassigned —
// hence non-word, hence a boundary bonus — on the other. Against Go 1.26.5 there are 16 such
// code points today, five of which also flip the smart-case decision for a whole query.
// Every one is a recently-assigned character no branch name contains, which is why this is a
// documented resync trigger rather than a correctness fix: the honest repair is regenerating
// the corpus on the newer toolchain, not hand-maintaining a divergence table.
const IS_LOWER = /\p{Ll}/u;
const IS_UPPER = /\p{Lu}/u;
const IS_NUMBER = /\p{N}/u;
const IS_LETTER = /\p{L}/u;
const IS_SPACE = /\p{White_Space}/u;

/**
 * Classes for non-ASCII code points, memoized.
 *
 * The uncached path builds a string and runs up to five regexes; a picker re-runs the
 * matcher on every keystroke over every row, so paying that once per distinct code point is
 * worth the map. Bounded by the distinct non-ASCII characters the caller actually passes.
 */
const nonAsciiClassCache = new Map<number, number>();

/** fzf's `charClassOfNonAscii`, in upstream's test order — the order decides ties. */
function charClassOfNonAscii(codePoint: number): number {
  const cached = nonAsciiClassCache.get(codePoint);
  if (cached !== undefined) return cached;

  const char = String.fromCodePoint(codePoint);
  let charClass = CHAR_NON_WORD;
  if (IS_LOWER.test(char)) charClass = CHAR_LOWER;
  else if (IS_UPPER.test(char)) charClass = CHAR_UPPER;
  else if (IS_NUMBER.test(char)) charClass = CHAR_NUMBER;
  else if (IS_LETTER.test(char)) charClass = CHAR_LETTER;
  else if (IS_SPACE.test(char)) charClass = CHAR_WHITE;
  // fzf's final `delimiterChars` check is unreachable here: every delimiter is ASCII.

  nonAsciiClassCache.set(codePoint, charClass);
  return charClass;
}

/**
 * U+0130 (`İ`), the one code point where Go's lowercase mapping and JavaScript's disagree
 * in a way that changes matching.
 *
 * Go applies the *simple* case mapping, one code point to one code point, and lowercases it
 * to `i`. `String#toLowerCase` applies the *full* mapping and expands it to `i` + U+0307. It
 * is the only unconditional single-to-multiple lowercase mapping in Unicode's SpecialCasing
 * data, so handling it by name is enough — but only for the table version the corpus was cut
 * against, since a frozen corpus pins the cases it contains and cannot announce a new one.
 * That is what makes a Unicode table bump a resync trigger.
 */
const DOTTED_CAPITAL_I = 0x0130;
const DOTTED_CAPITAL_I_LOWER = 0x0069;

/** Memo for {@link simpleToLower}, which otherwise allocates two strings and an array. */
const simpleLowerCache = new Map<number, number>();

/**
 * Go's `unicode.ToLower` for one code point.
 *
 * The general rule is "take JavaScript's answer unless the full mapping expanded it", which
 * agrees with Go everywhere except {@link DOTTED_CAPITAL_I}. Falling back to the original on
 * expansion would silently stop `İstanbul` from matching `i` — a case the corpus contains,
 * alongside ẞ, ß, ı and the sigmas.
 */
function simpleToLower(codePoint: number): number {
  if (codePoint === DOTTED_CAPITAL_I) return DOTTED_CAPITAL_I_LOWER;

  const cached = simpleLowerCache.get(codePoint);
  if (cached !== undefined) return cached;

  const lowered = String.fromCodePoint(codePoint).toLowerCase();
  const simple =
    Array.from(lowered).length === 1 ? (lowered.codePointAt(0) ?? codePoint) : codePoint;

  simpleLowerCache.set(codePoint, simple);
  return simple;
}

/** Splits a string into code points — `Int32Array.from` uses the string iterator, which
 * yields whole code points rather than UTF-16 units. */
function toCodePoints(value: string): Int32Array {
  return Int32Array.from(value, (char) => char.codePointAt(0) ?? 0);
}

/**
 * Fuzzy-matches `query` against `text`, returning fzf's score and match positions, or
 * `null` when `query` is not a subsequence of `text`.
 *
 * Case sensitivity is **smart**, exactly as fzf's `BuildPattern` decides it: an all-lowercase
 * query matches case-insensitively, and a single uppercase character anywhere in the query
 * makes the whole query case-sensitive.
 *
 * An empty query matches every text with a score of 0 and no positions, which is what lets a
 * picker show its full list before the user types.
 *
 * @param text - The candidate being scored, e.g. a branch name or a PR title.
 * @param query - The raw user query, before any case folding.
 * @returns The match, or `null` if there is none.
 */
export function fuzzyMatch(text: string, query: string): FuzzyMatch | null {
  // fzf lowercases the pattern when the query is case-insensitive — but a query is
  // case-insensitive precisely when lowercasing leaves it unchanged, so the fold is a no-op
  // and the raw query can go straight through. This also sidesteps the simple-versus-full
  // lowercasing divergence for the pattern side entirely.
  const caseSensitive = query.toLowerCase() !== query;
  return fuzzyMatchV2(caseSensitive, toCodePoints(text), toCodePoints(query));
}

/**
 * fzf's `FuzzyMatchV2`, phase for phase.
 *
 * Upstream expresses phase 3 with overlapping Go slices (`Hsub`, `Hleft`, `Hdiag`, `Cdiag`)
 * aliasing one backing array. Those are spelled out as explicit indices here, with each
 * one's upstream name in a comment, because TypeScript has no equivalent aliasing and a
 * half-translated mix of the two would be the easiest place in this file to introduce an
 * off-by-one.
 *
 * @param input - The text's code points. **Taken by reference and case-folded in place**,
 * exactly as fzf mutates its own rune array; the caller must not reuse it afterwards.
 */
function fuzzyMatchV2(
  caseSensitive: boolean,
  input: Int32Array,
  pattern: Int32Array,
): FuzzyMatch | null {
  const M = pattern.length;
  if (M === 0) return { score: 0, positions: [] };
  const N = input.length;
  if (M > N) return null;

  /** Row 0 of the score matrix: the pattern's first character against every position. */
  const H0 = new Int16Array(N);
  /** Length of the consecutive-match chunk ending at each position, in row 0. */
  const C0 = new Int16Array(N);
  /** Bonus for each position. */
  const B = new Int16Array(N);
  /** First occurrence of each pattern character, which bounds each row from the left. */
  const F = new Int32Array(M);
  /** The text, case-folded in place — fzf mutates its rune array the same way. */
  const T = input;

  // Phase 2. Bonuses, first occurrences, and row 0 of the score matrix, in one pass.
  let maxScore = 0;
  let maxScorePos = 0;
  let pidx = 0;
  let lastIdx = 0;
  const pchar0 = at(pattern, 0);
  let pchar = pchar0;
  let prevH0 = 0;
  let prevClass = INITIAL_CHAR_CLASS;
  let inGap = false;

  for (let off = 0; off < N; off++) {
    let char = at(T, off);
    let charClass: number;
    if (char <= ASCII_MAX) {
      charClass = at(ASCII_CHAR_CLASSES, char);
      if (!caseSensitive && charClass === CHAR_UPPER) {
        char += 32;
        T[off] = char;
      }
    } else {
      charClass = charClassOfNonAscii(char);
      if (!caseSensitive && charClass === CHAR_UPPER) char = simpleToLower(char);
      T[off] = char;
    }

    const bonus = at(BONUS_MATRIX, prevClass * CHAR_CLASS_COUNT + charClass);
    B[off] = bonus;
    prevClass = charClass;

    if (char === pchar) {
      if (pidx < M) {
        F[pidx] = off;
        pidx++;
        pchar = at(pattern, Math.min(pidx, M - 1));
      }
      lastIdx = off;
    }

    if (char === pchar0) {
      H0[off] = SCORE_MATCH + bonus * BONUS_FIRST_CHAR_MULTIPLIER;
      C0[off] = 1;
      if (M === 1 && at(H0, off) > maxScore) {
        maxScore = at(H0, off);
        maxScorePos = off;
        // The first boundary-bonus hit cannot be beaten by anything further right.
        if (bonus >= BONUS_BOUNDARY) break;
      }
      inGap = false;
    } else {
      H0[off] = Math.max(prevH0 + (inGap ? SCORE_GAP_EXTENSION : SCORE_GAP_START), 0);
      C0[off] = 0;
      inGap = true;
    }
    prevH0 = at(H0, off);
  }

  // The pattern never completed as a subsequence.
  if (pidx !== M) return null;
  if (M === 1) return { score: maxScore, positions: [maxScorePos] };

  // Phase 3. Fill the rest of the score matrix. Omission and mismatch are not allowed, so
  // each row is bounded left by its character's first occurrence and right by `lastIdx`.
  const f0 = at(F, 0);
  const width = lastIdx - f0 + 1;
  const H = new Int16Array(width * M);
  const C = new Int16Array(width * M);
  for (let column = 0; column < width; column++) {
    H[column] = at(H0, f0 + column);
    C[column] = at(C0, f0 + column);
  }

  for (let row = 1; row < M; row++) {
    const first = at(F, row);
    const pcharRow = at(pattern, row);
    const rowStart = row * width;
    let inRowGap = false;
    // Upstream's `Hleft[0] = 0`: the cell immediately left of this row's first column is
    // the row's left boundary, and must not inherit the previous row's tail.
    H[rowStart + first - f0 - 1] = 0;

    for (let column = first; column <= lastIdx; column++) {
      const offset = column - f0;
      const char = at(T, column);
      let s1 = 0;
      let consecutive = 0;

      // `Hleft[off]`. Annotated because `inRowGap` is assigned from a comparison against
      // `s2` further down, and inferring `s2` from a value that depends on its own previous
      // iteration is a cycle the checker refuses (TS7022).
      const s2: number =
        at(H, rowStart + offset - 1) + (inRowGap ? SCORE_GAP_EXTENSION : SCORE_GAP_START);

      if (pcharRow === char) {
        // `Hdiag[off]` and `Cdiag[off]` — the cell up-and-left.
        s1 = at(H, rowStart - width + offset - 1) + SCORE_MATCH;
        let bonus = at(B, column);
        consecutive = at(C, rowStart - width + offset - 1) + 1;
        if (consecutive > 1) {
          const chunkStartBonus = at(B, column - consecutive + 1);
          if (bonus >= BONUS_BOUNDARY && bonus > chunkStartBonus) {
            // A stronger boundary starts a new chunk rather than extending this one.
            consecutive = 1;
          } else {
            bonus = Math.max(bonus, BONUS_CONSECUTIVE, chunkStartBonus);
          }
        }
        if (s1 + bonus < s2) {
          s1 += at(B, column);
          consecutive = 0;
        } else {
          s1 += bonus;
        }
      }
      C[rowStart + offset] = consecutive;

      inRowGap = s1 < s2;
      // Stored before it is compared, so the comparison reads the value back through
      // `Int16Array` rather than seeing the wider JavaScript number.
      H[rowStart + offset] = Math.max(s1, s2, 0);
      if (row === M - 1 && at(H, rowStart + offset) > maxScore) {
        maxScore = at(H, rowStart + offset);
        maxScorePos = column;
      }
    }
  }

  // Phase 4. Backtrace from the best cell in the last row to recover the positions. A cell
  // is part of the match when it beats both the diagonal and the left neighbour; ties go to
  // a match when `preferMatch` says the run should continue.
  const positions: number[] = [];
  let row = M - 1;
  let column = maxScorePos;
  let preferMatch = true;
  for (;;) {
    const rowStart = row * width;
    const offset = column - f0;
    // Go's bounds checks would panic here; a typed array reads `undefined` instead, every
    // comparison below goes false, and the loop walks left forever. The invariant that
    // stops it is that at `column === F[row]` the diagonal is beaten outright, so the row
    // always steps up — but an infinite loop on the picker's keystroke path is the one
    // failure worth spending a line to make loud.
    if (offset < 0) throw new Error("fuzzy backtrace ran past the score matrix");
    const score = at(H, rowStart + offset);

    let diagonal = 0;
    let left = 0;
    if (row > 0 && column >= at(F, row)) diagonal = at(H, rowStart - width + offset - 1);
    if (column > at(F, row)) left = at(H, rowStart + offset - 1);

    const currentRow = row;
    if (score > diagonal && (score > left || (score === left && preferMatch))) {
      positions.push(column);
      if (row === 0) break;
      row--;
    }
    // The `column + 1 >= F[row + 1]` and `column >= F[row]` guards are redundant here:
    // upstream reuses one slab across calls, so those cells can hold stale data from an
    // earlier match, whereas these matrices are freshly zeroed and `C` is only ever written
    // inside `[F[row], lastIdx]`. They are kept anyway — this loop's whole maintenance story
    // is that it reads line-for-line against `algo.go`'s.
    preferMatch =
      at(C, rowStart + offset) > 1 ||
      (currentRow + 1 < M &&
        column < lastIdx &&
        column + 1 >= at(F, currentRow + 1) &&
        at(C, rowStart + width + offset + 1) > 0);
    column--;
  }

  positions.reverse();
  return { score: maxScore, positions };
}
